################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.c \
../ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.c 

SREC += \
renesas-RA6E1-speech-recognition.srec 

C_DEPS += \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.d \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.d 

OBJS += \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_32x64_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df1_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_df2T_init_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_biquad_cascade_stereo_df2T_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_opt_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_opt_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_partial_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_conv_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_opt_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_correlate_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_decimate_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_fast_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_f64.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_init_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_interpolate_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_lattice_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_init_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_fir_sparse_q7.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_iir_lattice_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f16.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_levinson_durbin_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_f32.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_init_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_norm_q31.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q15.o \
./ra/arm/CMSIS-DSP/Source/FilteringFunctions/arm_lms_q31.o 

MAP += \
renesas-RA6E1-speech-recognition.map 


# Each subdirectory must supply rules for building sources it contributes
ra/arm/CMSIS-DSP/Source/FilteringFunctions/%.o: ../ra/arm/CMSIS-DSP/Source/FilteringFunctions/%.c
	$(file > $@.in,-mcpu=cortex-m33 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16 -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fpermissive -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal -g -D_RENESAS_RA_ -D_RA_CORE=CM33 -D_RA_ORDINAL=1 -I"C:/d_disk/RenesasMCUHWM/RCar/Gen4/R-Car_V4M/code/VoiceRecognization/renesas-RA6E1-speech-recognition/src" -I"C:/d_disk/RenesasMCUHWM/RCar/Gen4/R-Car_V4M/code/VoiceRecognization/renesas-RA6E1-speech-recognition/ra/fsp/inc" -I"C:/d_disk/RenesasMCUHWM/RCar/Gen4/R-Car_V4M/code/VoiceRecognization/renesas-RA6E1-speech-recognition/ra/fsp/inc/api" -I"C:/d_disk/RenesasMCUHWM/RCar/Gen4/R-Car_V4M/code/VoiceRecognization/renesas-RA6E1-speech-recognition/ra/fsp/inc/instances" -I"C:/d_disk/RenesasMCUHWM/RCar/Gen4/R-Car_V4M/code/VoiceRecognization/renesas-RA6E1-speech-recognition/ra_gen" -I"C:/d_disk/RenesasMCUHWM/RCar/Gen4/R-Car_V4M/code/VoiceRecognization/renesas-RA6E1-speech-recognition/ra_cfg/fsp_cfg/bsp" -I"C:/d_disk/RenesasMCUHWM/RCar/Gen4/R-Car_V4M/code/VoiceRecognization/renesas-RA6E1-speech-recognition/ra_cfg/fsp_cfg" -I"C:/d_disk/RenesasMCUHWM/RCar/Gen4/R-Car_V4M/code/VoiceRecognization/renesas-RA6E1-speech-recognition/src/third_party/gemmlowp" -I"C:/d_disk/RenesasMCUHWM/RCar/Gen4/R-Car_V4M/code/VoiceRecognization/renesas-RA6E1-speech-recognition/src/third_party/ruy" -I"C:/d_disk/RenesasMCUHWM/RCar/Gen4/R-Car_V4M/code/VoiceRecognization/renesas-RA6E1-speech-recognition/src/third_party/kissfft" -I"C:/d_disk/RenesasMCUHWM/RCar/Gen4/R-Car_V4M/code/VoiceRecognization/renesas-RA6E1-speech-recognition/src/third_party/flatbuffers/include" -I"C:/d_disk/RenesasMCUHWM/RCar/Gen4/R-Car_V4M/code/VoiceRecognization/renesas-RA6E1-speech-recognition/ra/arm/CMSIS_6/CMSIS/Core/Include" -I"." -I"C:/d_disk/RenesasMCUHWM/RCar/Gen4/R-Car_V4M/code/VoiceRecognization/renesas-RA6E1-speech-recognition/ra/arm/CMSIS-DSP/PrivateInclude" -I"C:/d_disk/RenesasMCUHWM/RCar/Gen4/R-Car_V4M/code/VoiceRecognization/renesas-RA6E1-speech-recognition/ra/arm/CMSIS-DSP/Include" -std=c99 -Os -w -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" -x c "$<")
	@echo Building file: $< && arm-none-eabi-gcc @"$@.in"

